retrieve_news_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: retrieve_news

scrape_website_task:
  description: >
    Scrape the website for the latest news and information.
  expected_output: >
    A list of the latest news and information from the website.
  agent: website_scraper


ai_news_writer_task :
  description: >
    Summarize the information from the website into a fully fledged news article in markdown format.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: ai_news_writer

file_writer_task:
  description: >
    Write the news article to a file. Create the 'news' directory if it doesn't exist.
  expected_output: >
    A fully fledged news article in markdown format into a file named news/{date}_news_article.md.
    The news directory will be created if it doesn't exist.
  agent: file_writer
